import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ConvexClientProvider } from '@/components/ConvexClientProvider'
import Link from 'next/link'
import { cn } from '@/lib/utils'
import { Button, buttonVariants } from '@/components/ui/button'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <ConvexClientProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <header className="flex justify-between items-center p-4 gap-4">
              <Link href="/">
                <h1 className="text-2xl">
                  ⚽️
                </h1>
              </Link>
              <div className="flex gap-4 items-center">
                <SignedOut>
                  <SignInButton>
                    <Button>Login</Button>
                  </SignInButton>
                </SignedOut>
                <SignedIn>
                  <Link href="/dashboard" className={cn(buttonVariants())}>Dashboard</Link>
                  <UserButton />
                </SignedIn>
              </div>
            </header>
            <div className="p-8 sm:px-12 sm:py-4">
              {children}
            </div>
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  )
}